MyDevOrgData/src/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDevOrgData/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDevOrgData/src/classes/CustomerUpdateTest.cls
@isTest
public class CustomerUpdateTest 
{
    public static testMethod void test()
  {
	Customer__c Cust = new Customer__c();
    Cust.Name = 'test class name';
    Cust.Salary__c = 1000;
    Cust.Phone__c = '1234567890';
    insert Cust;
    Cust.Salary__c = 3000;
    Cust.Phone__c = '0987654321';
    update Cust;
    Test__c t = new Test__c();
      t.Name = 'test  name';
      t.Salary__c=Cust.Salary__c;
      insert t;
  }
}